# create supplier
POST http://localhost:8000/api/v1/user/register
Content-Type: application/json

{
  "email": "shop@shop.ru",
  "password": "Newshop",
  "type": "shop"
}

###

POST http://localhost:8000/api/v1/user/register/confirm
Content-Type: application/json

{
  "email": "shop@shop.ru",
  "token": "0ec09c15dbeb2d347f20e285fdd16dbeefe3f89e"
}

###

POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
  "email": "shop@shop.ru",
  "password": "Newshop"
}

###

GET http://localhost:8000/api/v1/partner/state
Authorization: Token a5d9e2acf7d4f2d7186fe348abcf2fbb8d5679cb

###

POST http://localhost:8000/api/v1/partner/state
Authorization: Token a5d9e2acf7d4f2d7186fe348abcf2fbb8d5679cb
Content-Type: application/json

{
  "state": "True"
}

###
POST http://localhost:8000/api/v1/partner/update
Authorization: Token a5d9e2acf7d4f2d7186fe348abcf2fbb8d5679cb
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="shop1.yaml"

< ./shop1.yaml
--WebAppBoundary--

###

# create buyer
POST http://localhost:8000/api/v1/user/register
Content-Type: application/json

{
"email": "buyer@buyer.ru",
"password": "Newbuyer"
}

###

POST http://localhost:8000/api/v1/user/register/confirm
Content-Type: application/json

{
"email": "buyer@buyer.ru",
"token": "97ea99e0f88ac7ba8528c9cbe"
}

###

POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
"email": "buyer@buyer.ru",
"password": "Newbuyer"
}

###

GET http://localhost:8000/api/v1/partner/state
Authorization: Token 43da1cae50c510f0d1865a739b87c20d4aa67493
Content-Type: application/json

###

POST http://localhost:8000/api/v1/user/contact
Authorization: Token 43da1cae50c510f0d1865a739b87c20d4aa67493
Content-Type: application/json

{
  "city": "Воронеж",
  "street": "Плехановская",
  "house": "31",
  "apartment": "15",
  "phone": "+7800800800"
}

###

GET http://localhost:8000/api/v1/user/contact
Authorization: Token 43da1cae50c510f0d1865a739b87c20d4aa67493

###

DELETE http://localhost:8000/api/v1/user/contact/10/
Authorization: Token 43da1cae50c510f0d1865a739b87c20d4aa67493

###

GET http://localhost:8000/api/v1/shops/
Authorization: Token 43da1cae50c510f0d1865a739b87c20d4aa67493

###

GET http://localhost:8000/api/v1/categories/
Authorization: Token 43da1cae50c510f0d1865a739b87c20d4aa67493

###

GET http://localhost:8000/api/v1/products/
Authorization: Token 43da1cae50c510f0d1865a739b87c20d4aa67493

###