version: '3.8'

services:

  db:
    image: postgres:14
    container_name: diploma_db
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"

  smtp-server:
    image: mailhog/mailhog:latest
    container_name: smtp-server
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6380:6379'
#  celery:
#    restart: always
#    container_name: celery
#    image: celery:latest
#    command: celery -A orders worker -l info
#    depends_on:
#      - postgres
#      - redis
