version: '3.8'

services:

  db:
    image: postgres:14
    container_name: diploma_db
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"

  smtp-server:
    image: mailhog/mailhog:latest
    container_name: smtp-server
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
