# Generated by Django 4.0.4 on 2022-04-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('buyer', 'Покупатель'), ('shop', 'Магазин')], default='buyer', max_length=5, verbose_name='Тип пользователя'),
        ),
    ]
