# Generated by Django 4.0.4 on 2022-04-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='apartment',
            field=models.CharField(max_length=15, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='house',
            field=models.CharField(max_length=15, verbose_name='Дом'),
        ),
    ]
