# Generated by Django 4.0.4 on 2022-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_state_alter_shop_url_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='Пользователь', help_text='Поле необязательное', max_length=100),
        ),
    ]
